# Generated by Django 3.0.8 on 2020-07-29 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
