# Generated by Django 3.0.8 on 2020-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200729_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
