# Generated by Django 3.0.8 on 2020-07-29 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_auto_20200729_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='guest',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='desc',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Bokking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel')),
            ],
        ),
    ]
